version: '3.8'

services:
  django-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - django-db
    environment:
      DB_HOST: django-db
      DB_NAME: djangodb
      DB_USER: postgres
      DB_PASSWORD: root
    volumes:
      - .:/app

  django-db:
    image: postgres:16
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - django-db-data:/var/lib/postgresql/data

volumes:
  django-db-data:
