# Generated by Django 5.1.7 on 2025-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('year', models.IntegerField(default=2025)),
                ('color', models.CharField(default='', max_length=50)),
                ('registration_plate', models.CharField(default='2025', max_length=50)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
