# Generated by Django 5.1.7 on 2025-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
