version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - spring-db
    environment:
      DB_HOST: spring-db
      DB_NAME: springdb
      DB_USER: postgres
      DB_PASSWORD: root

  spring-db:
    image: postgres:16
    environment:
      POSTGRES_DB: springdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
    - "5432:5432"
    volumes:
      - spring-db-data:/var/lib/postgresql/data

volumes:
  spring-db-data:
